# netlify.toml

[build]
  base    = "react-tailwind-vanilla"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Proxy all API calls to Render (kills CORS)
[[redirects]]
  from = "/api/*"
  to   = "https://solarsense-api.onrender.com/:splat"
  status = 200
  force  = true

# SPA fallback so refresh works
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
