[build]
  base = "react-tailwind-vanilla"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# Proxy first (avoids CORS)
[[redirects]]
  from = "/api/*"
  to   = "https://solarsense-api.onrender.com/:splat"
  status = 200
  force = true

# SPA fallback last
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
