# netlify.toml  (repo root)

[build]
  # your frontend lives here:
  base = "react-tailwind-vanilla"
  command = "npm ci && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"        # Netlify's Node for webpack build

# SPA fallback so client-side routes work on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
