name: solarsense-predictor
channels: [conda-forge, pytorch]
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - numpy
  - pandas
  - requests
  - scikit-learn
  - pip
  - pip:
      - torch==2.2.2+cpu --extra-index-url https://download.pytorch.org/whl/cpu
