name: solarsense
channels:
  - conda-forge
dependencies:
  - python=3.11
  - fastapi
  - uvicorn
  - numpy
  - pandas
  - requests
  - scikit-learn
  # astropy is fine (light); sunpy is intentionally omitted for Render
  - astropy
  - pip
  # no pip torch here; we install torch in the Dockerfile with a custom index
